# This file was generated by GoReleaser. DO NOT EDIT.
cask "castctl" do
  name "castctl"
  desc "CAST AI CLI"
  homepage "https://cast.ai"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "castctl"

  on_macos do
    on_intel do
      url "https://storage.googleapis.com/castctl/#{version}/castctl_darwin_amd64.tar.gz"
      sha256 "bc021b2d38bfb134ceb38457f0dc174414b93921d424c81aac5a33dc3d7ff0c6"
    end
    on_arm do
      url "https://storage.googleapis.com/castctl/#{version}/castctl_darwin_arm64.tar.gz"
      sha256 "fef1de576a4305a48cb034f21c82073a6ef144f5e120b8d61d4b5b4b03b9cc4c"
    end
  end

  on_linux do
    on_intel do
      url "https://storage.googleapis.com/castctl/#{version}/castctl_linux_amd64.tar.gz"
      sha256 "abb897013509a8e7a81c2d222248c0c0ffa0f4376a39fd76d3a9e497ac6d05f2"
    end
    on_arm do
      url "https://storage.googleapis.com/castctl/#{version}/castctl_linux_arm64.tar.gz"
      sha256 "47dda6ce9e5ec21f1ea347c809321f2632cf924d1bab09012a23bbcc069838bf"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/castctl"]
    end
  end

  # No zap stanza required
end
