# This file was generated by GoReleaser. DO NOT EDIT.
cask "castctl" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "aa5cf0c84bbeaa361d087a6e05e0c5527b4153591accf7b1a19340988b6a0d82"
      url "https://storage.googleapis.com/castai-castctl/#{version}/castctl_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6879a433b03fffce4c9dbb6c9802d3250a1d206fe1638e5b8c0922257fa74f87"
      url "https://storage.googleapis.com/castai-castctl/#{version}/castctl_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "66281abf9d966ee7f0e662c595d54615af2525a7cc1a6e82f2ae358e37add3b0"
      url "https://storage.googleapis.com/castai-castctl/#{version}/castctl_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "212114f3b3229301f86e4447610a42cd4c74165330fa09e56e6d393d055d1947"
      url "https://storage.googleapis.com/castai-castctl/#{version}/castctl_linux_arm64.tar.gz"
    end
  end

  name "castctl"
  desc "CAST AI CLI"
  homepage "https://cast.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "castctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/castctl"]
    end
  end

  # No zap stanza required

end
