# This file was generated by GoReleaser. DO NOT EDIT.
cask "castctl" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "04670231cb8112ba49870186e9d7b52a5b8325fc0ae0c0f679252fded5254ef0"
      url "https://storage.googleapis.com/castai-castctl/#{version}/castctl_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "45dd67f8e51cc9da9fc3ded4baf167b152e2b1109233ecab5fc3b76083ede0c4"
      url "https://storage.googleapis.com/castai-castctl/#{version}/castctl_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2c072d5afc29df0b0b1b341f3f42658f116705620dbedf2b6430609399d72cfc"
      url "https://storage.googleapis.com/castai-castctl/#{version}/castctl_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "642623e41289f34224cbdbb6fc858f28537cbbe5698d176579814cf3e3074d01"
      url "https://storage.googleapis.com/castai-castctl/#{version}/castctl_linux_arm64.tar.gz"
    end
  end

  name "castctl"
  desc "CAST AI CLI"
  homepage "https://cast.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "castctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/castctl"]
    end
  end

  # No zap stanza required

end
