# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CastCli < Formula
  desc "Multiple clouds in one K8s cluster. Best combination of everything in cloud"
  homepage "https://cast.ai"
  version "0.0.7"
  license "Apache License"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/castai/cast-cli/releases/download/v0.0.7/cast-cli_0.0.7_darwin_amd64.zip"
    sha256 "c243881d72e447ee3df0abd6190626dbe0c0d8b34348de97b788be608d328c56"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/castai/cast-cli/releases/download/v0.0.7/cast-cli_0.0.7_linux_amd64.zip"
    sha256 "d111ab62e13aa0405280327924967e3c0308e6cc226672339be947e7540edb74"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/castai/cast-cli/releases/download/v0.0.7/cast-cli_0.0.7_linux_arm64.zip"
    sha256 "9f7a890a242127141803570e6a5ff1e2c86aa93a49f6bf84289acbdb81ecbf67"
  end

  def install
    bash_completion.install "completions/goreleaser.bash" => "cast"
    zsh_completion.install "completions/goreleaser.zsh" => "_cast"
    fish_completion.install "completions/goreleaser.fish"
  end

  test do
    system "#{bin}/cast version"
  end
end
