# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Multiple clouds in one K8s cluster. Best combination of everything in cloud"
  homepage "https://cast.ai"
  version "0.9.0"
  license "Apache License"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/castai/cli/releases/download/v0.9.0/cli_0.9.0_darwin_amd64.zip"
    sha256 "41eb5a87c51c1a1584ea79ce108c5572a5ae7020912028cbea7704fe2f451e27"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/castai/cli/releases/download/v0.9.0/cli_0.9.0_linux_amd64.zip"
    sha256 "96dc0611bf9dabeb5e9b9c18802349c9f2479386d7ec050d51d11eed80e6fdb5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/castai/cli/releases/download/v0.9.0/cli_0.9.0_linux_arm64.zip"
    sha256 "a4a2a02309986df56b7bce74d15216e06ad2eca8e23f87a96ddef56215112aa2"
  end

  def install
    bin.install "cast"
    bash_completion.install "completions/cast.bash" => "cast"
    zsh_completion.install "completions/cast.zsh" => "_cast"
    fish_completion.install "completions/cast.fish"
  end

  test do
    system "#{bin}/cast version"
  end
end
