# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Multiple clouds in one K8s cluster. Best combination of everything in cloud"
  homepage "https://cast.ai"
  version "0.4.0"
  license "Apache License"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/castai/cli/releases/download/v0.4.0/cli_0.4.0_darwin_amd64.zip"
    sha256 "d1c99bbe1a15ea7410aa6f66dd02d2a8341c37e30bb1cc71111a903df18460a6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/castai/cli/releases/download/v0.4.0/cli_0.4.0_linux_amd64.zip"
    sha256 "d307871ddf709b9448767fac464ad882bb6ab1822e759e2ae24f93064d9eae33"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/castai/cli/releases/download/v0.4.0/cli_0.4.0_linux_arm64.zip"
    sha256 "86ec4689666219c5b93ff1ec41d4e0c3af8e9955102325f8a040cdafbce1a507"
  end

  def install
    bin.install "cast"
    bash_completion.install "completions/cast.bash" => "cast"
    zsh_completion.install "completions/cast.zsh" => "_cast"
    fish_completion.install "completions/cast.fish"
  end

  test do
    system "#{bin}/cast version"
  end
end
